# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  -  id: trailing-whitespace
  -  id: end-of-file-fixer
  -  id: check-yaml
  -  id: check-added-large-files

- repo: https://github.com/ambv/black
  rev: 21.10b0
  hooks:
  - id: black
    language_version: python3.8

- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
  - id: isort
    name: isort (python)
    args: ["--profile", "black"]

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a4
  hooks:
  - id: pylint

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.7.2.1
  hooks:
    - id: shellcheck

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.29.0
  hooks:
  - id: markdownlint
    args: ["--ignore", "mynewbook"]
