- name: Data Study Group
  files:
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - communication/communication
    - communication/comms-overview
    - communication/comms-overview/comms-overview-principles
    - collaboration/collaboration
    - collaboration/github-novice
    - collaboration/github-novice/github-novice-advanced
    - collaboration/leadership
  colour: white
  description: consectetur adipiscing elit. Sed nec mauris quis magna consequat consequat vel quis odio. Sed nec arcu malesuada, aliquam erat eget, bibendum nisi. Nunc varius, odio eu molestie euismod, sapien ipsum vulputate eros, sed lacinia nisl sapien eu nisi. Nulla facilisi. Nullam vulputate, odio sed tempor rutrum, est ipsum ultrices lorem, a feugiat velit magna in metus.

- name: PhD Students
  files:
    - communication/communication
    - communication/comms-overview
    - communication/comms-overview/comms-overview-principles
    - reproducible-research/reproducible-research
    - reproducible-research/overview
  colour: blue
  description: PhD students are early career researchers who may not have a lot of hands on experience with contributing to research projects from the start to finish. This curated set of chapters will allow them to understand what practices apply to their research at different stages of development.

- name: Group Leaders
  files:
    - project-design/project-design
    - project-design/pd-overview
    - project-design/pd-overview/pd-overview-planning
    - project-design/pd-overview/pd-overview-repro
    - project-design/pd-overview/pd-overview-methods
    - project-design/pd-overview/pd-overview-version
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-definitions
    - reproducible-research/overview/overview-benefit
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - reproducible-research/open
    - reproducible-research/open/open-data
    - reproducible-research/open/open-source
  colour: purple
  description: Fusce euismod mi eget neque sollicitudin, ut rhoncus tellus bibendum. Duis vitae fermentum quam, at bibendum nibh. Proin eu tellus turpis. Aliquam sodales eleifend sapien, vel fringilla risus faucibus at. Fusce vulputate libero eget ipsum dapibus, ut convallis est pharetra. Maecenas in dolor mauris.

- name: Life Scientists
  files:
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-benefit
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - reproducible-research/open
    - reproducible-research/open/open-data
    - reproducible-research/open/open-source
  colour: green
  description: Nullam sed dolor erat. Sed gravida metus at leo commodo, sed rutrum elit accumsan. Fusce vestibulum, velit ac imperdiet mattis, eros nisl luctus augue, ut bibendum risus magna eu velit. Morbi pharetra mauris sed sagittis feugiat. Duis scelerisque quam ac urna faucibus dignissim. Sed vel blandit sapien, id lacinia risus. Donec sit amet quam vestibulum, imperdiet felis non, rhoncus velit.
