- name: Dsg
  files:
    - welcome
    - communication/communication
    - communication/comms-overview
    - communication/comms-overview/comms-overview-principles
  colour: brown
- name: 'enrichment students'
  files:
    - welcome
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-definitions
  colour: green
- name: group-leader
  files:
    - welcome
    - communication/communication
    - communication/comms-overview
    - communication/comms-overview/comms-overview-principles
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-definitions
    - reproducible-research/overview/overview-benefit
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - reproducible-research/open
    - reproducible-research/open/open-data
    - reproducible-research/open/open-source
    - project-design/project-design
    - project-design/pd-overview
    - project-design/pd-overview/pd-overview-planning
    - project-design/pd-overview/pd-overview-repro
    - project-design/pd-overview/pd-overview-methods
    - project-design/pd-overview/pd-overview-version
  colour: purple
