dsg:
  - welcome
  - communication/communication
  - communication/comms-overview
  - communication/comms-overview/comms-overview-principles
enrichment:
  - welcome
  - reproducible-research/reproducible-research
  - reproducible-research/overview
  - reproducible-research/overview/overview-definitions