name: Pre-Commit Checks
on:
  [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('pathways/poetry.lock') }}

      - name: Install Requirements
        run: |
          pip install pathways/

      - name: pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --files pathways/**/* 

      - name: Run unit tests
        run: |
          cd pathways/ && ./run_tests.sh
