name: Pre-Commit Checks
on:
  pull_request:
    branches:
      main
  push:
    branches:
      main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      # Will run our tests with coverage for us
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --files main.py tests/test_main.py

      - name: Run unit tests
        run: |
          ./run_tests.sh
