name: Pre-Commit Checks
on:
  [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pathways
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Print Working Dir
        shell: bash
        run: |
          pwd

      - name: Bootstrap poetry
        shell: bash
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Configure poetry
        shell: bash
        run: |
          python -m poetry config virtualenvs.in-project true
          python -m poetry config virtualenvs.create true

      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m poetry install

      # Only used to install pre-commit, not to run it
      - name: Install pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --files path/does/not/exist/*

      # Now we install the hooks and run pre-commit
      - name: Local pre-commit
        shell: bash
        run: |
          pre-commit install
          pre-commit run --all-files

      - name: Run unit tests
        run: |
          poetry run ./run_tests.sh
